### ISSUE TITLE
Rich app section issues

### ISSUE THREAD

**Issue by loskov** [kdabir/awesome-groovy#18]
In table of contents Desktop App Framworks points to:
https://github.com/kdabir/awesome-groovy/blob/master/rich-applications (goes 404)
and should point to:
https://github.com/kdabir/awesome-groovy#rich-application

Inside Rich Application section Griffon link still points to Codehaus.
New address for Griffon should be http://griffon-framework.org/

**Comment by kdabir** [comment]
Issue fixed by f053bcf. Thanks for reporting.
